config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  get 'users/search' => 'users#search'
  resources :groups, except: [:show, :destroy] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :group_name, presence: true
  has_many  :user_groups
  has_many  :messages
  has_many  :users, through: :user_groups
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true
  validates_format_of :password, with: /([0-9].*[a-zA-Z]|[ a-zA-Z].*[0-9])/, on: :create
  has_many :user_groups
  has_many :groups, through: :user_groups
  has_many :messages
  accepts_nested_attributes_for :groups

  scope :search_with_name, -> (name){where("name like ?","%#{name}%")}

end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  before_action :authenticate_user!

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  # before_action :after_sign_out_pass_for, if: :devise_controller?

  def after_sign_out_pass_for
    'new_user_sesson'
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :set_group, only:[:edit, :update]

  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループが作成されました。'
    else
      flash[:alert] = '新規のグループが作成されませんでした'
      render "new"
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループが更新されました。'
    else
      flash[:alert] = 'グループが更新されませんでした'
      render "edit"
    end
  end

  private
  def group_params
    params.require(:group).permit(:group_name, user_ids: [])
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :set_group, :set_groups, :set_messages, only:[:index, :create]

  def index
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to :group_messages, notice: "メッセージが投稿されました" }
        format.json
      end
    else
      flash[:alert] = "メッセージを入力してください"
      render :index
    end
  end

  private

  def message_params
    params
      .require(:message)
      .permit(:image, :body)
      .merge(
        user_id: current_user.id,
        group_id: params[:group_id]
      )
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

  def set_groups
    @groups = current_user.groups
  end

  def set_messages
    @messages = @group.messages
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def search
    @users = []
    @users = User.search_with_name(params[:name])
    respond_to do |format|
      format.json
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/groups/_form.html.haml
= form_for @group do |f|
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      =f.label :group_name, "グループ名", class: "chat-group-form__label"
    .chat-group-form__field--right
      =f.text_field :group_name, placeholder: "グループ名を入力してください", class: "chat-group-form__input"
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      =f.label :user, "チャットメンバーを追加", class: "chat-group-form__label"
    .chat-group-form__field--right
      =text_field_tag :user,"", placeholder: "追加したいユーザー名を入力してください", class: "chat-group-form__input", id: 'keyword'
      #user-search-result
        %ul.clearfix
          %li.user_list.clearfix
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right.clearfix
        = f.label "チャットメンバー", class: "chat-group-form__label"
        .remove-input
          %ul.clearfix
            %li.master-user #{current_user.name}
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        =f.submit "Save", class: "chat-group-form__action-btn"

app/views/groups/_group.haml
=link_to group_messages_path(group) do
  %ul.groups
    %li.group
      .group__name
        = group.group_name
      .group__text GoodByeWorld!!

app/views/groups/_leftcontent.haml
=link_to group_messages_path(group) do
  %ul.groups
    %li.group
      .group__name
        = group.group_name
      .group__text GoodByeWorld!!

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  =render partial: "form"

app/views/groups/index.html.haml
.left-contents
  .left__top-content
    %h1
      = current_user.name
    =link_to edit_user_registration_path, class: "btn btn-metis1 btn-sm" do
      %i.fa.fa-cog.fa-lg
    =link_to new_group_path, class: "btn btn-metis2 btn-sm" do
      %i.fa.fa-pencil-square-o.fa-lg
  .left__bottom-content
    = render partial: "groups/group", collection: @groups, as: "group"

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  =render partial: "form"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - if flash[:notice]
      %p.alert.alert-info= notice
    - if flash[:alert]
      %p.alert.alert-error= alert
    .contents
      =yield

app/views/messages/_left.haml
%ul.groups
  %li.group
    .group__name
      = group.group_name
    .group__text GoodByeWorld!!

app/views/messages/index.html.haml
= render template: "groups/index"
.right-contents
  .right__top-content
    %span
      .group_name
        = @group.group_name
    %span
      .members
        - @group.users.each do |user|
          = user.name
    =link_to "Edit", edit_group_path(@group), class: "button1"
  .right__center-content
    .messages
      - @messages.each do |message|
        %span
          .messages__member= message.user.name
        %span
          .messages__date= message.created_at
        %span
          .messages__text= message.body
  = form_for [@group, @message],html: {class: "js-form"} do |f|
    .right__bottom-content
      = f.text_field :body, placeholder: "type a message", class: "textarea"
      %i.fa.fa-picture-o.fa-lg
      = f.submit "Send", class: "button2"